# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ecea87b0aecf25726c1dcd740defb219eb9502717bc6b1ae794afc76685f65b775cc8e981703dcd46a7aef537bc44fc9c90325dabf258ee5347c0fa3feb9dc61

test:
  secret_key_base: 66fbf403a8b65b7189e6a243c9d85e2d3e15a42b6d226d0027cabed80f7ffc135df43e6db7d37c101d40e18559b1f1b3f7f38bbec8a927eed8b46ebaf65b3bfb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
